[package]
name = "patch_server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
log = "0.4.27"
md5 = "0.7.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
simplelog = "0.12.2"
toml = "0.8.22"
